### ISSUE TITLE
Shipping options not showing

### ISSUE THREAD

**Issue by mabolek** [meanbee/royalmail#64]
Hi!

I'm running a Magento 1.9.2.4 install with Meanbee_Royalmail 2.7.6 on a CentOS server with PHP 5.5. After the latest upgrade (or around that time), some products have stopped displaying Standard First Class shipping options.

I have a few products with this issue, but my test product weighs 800 grams and I have selected grams as the unit in Meanbee_Royalmail. When I enter a UK postal code and click "estimate" in the "Estimate Shipping and Tax" box, nothing much happens and the box stays as it is. Changing the weight to 100 grams makes no difference.

When I enable the "signed for" shipping options, I get shipping estimates for those.

I changed the Standard First Class lines in  lib/Meanbee/RoyalmailPHPLibrary/data/3_deliveryMethodMeta.csv so they're similar to those of "Signed for" (basically substituting "20" with "50"). Now it suddenly starts working and Standard First Class options show up. I don't know why, but maybe you can help me understand what's happening.

It's important to note that other products work fine and show shipping options without this issue, independent of weight.

Thank you for your assistance in resolving this issue.

Yours,

Mathias

**Comment by RidRack** [comment]
Hi Mathias!

It sounds like this is being caused by the cart price. The calculation for the methods is based on the weight of the cart, price of the cart and the available methods so it's likely that since you're under the weight of the methods you need and able to send them it's the cart price on the method. 

We've taken Royal Mails maximum insurance values for each method and put that as a limiting factor on which methods show up to be available. If you wan't to ignore those, feel free to change the values to a higher number. The best place to see how the CSV's are formatted is [the readme here](https://github.com/meanbee/royalmail-php-library). Please be sure to change the insurance value for all the place where the methods are mentioned to ensure there are no errors. 

If this doesn't resolve your issue, please let me know.

**Comment by mabolek** [comment]
Hi!

Thank you for the answer. I'm pretty certain that must be the cause of the issue.

**Suggested feature:** Maybe it would be a good idea to have a check-box for "ignore shipping insurance maximum". Either per product or shop-wide. Some products may be relatively cheap to replace for the store owner, even though it sells at more than £20. Some products in this store are - litterally - cow manure.


Yours,

Mathias

**Comment by RidRack** [comment]
Hi, 

Glad we could find the issue. We're actually considering that as a feature already as a number of users have asked for it. I'm going to mark this closed, glad we could find the issue. 

- RidRack
