### ISSUE TITLE
Adding international parcelforce data to CSV files

### ISSUE THREAD

**Issue by wsenjer** [meanbee/royalmail#73]
Hello there,
Currently, there is no option to ship products with a weight more than 2kg internationally. 
Are you planning to add the ParcelForce zones to the data CSV files? http://www.parcelforce.com/sites/default/files/price_guide_march_2015.pdf
If you don't have the time, can you please let me know what is the required steps to do that?

**Comment by RidRack** [comment]
Hi Wsenjer, 

We currently only use the Parcelforce methods for the UK, as the adding in the full usage for Parcelforce International methods adds a lot of extra methods to support and many more shipping zones. Apologies that this doesn't suit your situation!

We've used the royal mail price guide exclusively (http://www.royalmail.com/sites/default/files/RoyalMail_2016_Prices.pdf) as adding all of the Parcelforce methods adds a lot of other complexity, mostly because they have a completely different method of calculating the shipping zones to royal mail which would require a different shipping method and many more CSV files. 

If you still want to add in the Parcelforce methods, you would essentially have to add in specific calculation of the new methods, additional csv files with the methods from Parcelforce, and modify the library and extension files to account for this. If you'd like to best understand how the methods are being calculated currently, our FAQ has a good run through: https://meanbee.atlassian.net/wiki/display/EXT/Royal+Mail

The php library repository has a description of the CSV files as well: https://github.com/meanbee/royalmail-php-library

If you'd like any further information, I'm happy to help.
